apiVersion: v1
kind: Pod 
metadata: 
        name: test1 
        labels: 
                tavant: kubernetes 
spec: 
        containers: 
                - image: quay.io/mayank123modi/mynginx
                  name: mayank
